In [1]:
import pandas as pd

In [2]:
lyu_basic_nli = pd.read_parquet("/share/pierson/matt/mllmsci/outputs/vqa/bayflood_926k_10pct_lyu_basic_with_nli.parquet")

In [3]:
lyu_basic_nli.head()

,sample_id,prompt,image_path,image_url,image_base64,answer,model_response,nli_label,nli_score,nli_is_flooded
0,nexar_53afeec954a80d924012432cb70c1081,Analyze and estimate the deepest floodwater le...,/share/ju/nexar_data/2023/2023-09-29/604222325...,None,None,"Based on the image, the floodwater level can b...","Based on the image, the floodwater level can b...","yes, flooded",0.996216,True
1,nexar_66384e02c4b2ceda1b331f44ee45e950,Analyze and estimate the deepest floodwater le...,/share/ju/nexar_data/2023/2023-09-29/604222325...,None,None,"Based on the image, the floodwater level can b...","Based on the image, the floodwater level can b...","no, not flooded",0.955150,False
2,nexar_85283d2860cd54b22ccef4a210602830,Analyze and estimate the deepest floodwater le...,/share/ju/nexar_data/2023/2023-09-29/604222325...,None,None,The floodwater level in the image can be estim...,The floodwater level in the image can be estim...,"yes, flooded",0.989870,True
3,nexar_4bba636e205d574c150ba661ba3d5e35,Analyze and estimate the deepest floodwater le...,/share/ju/nexar_data/2023/2023-09-29/604222325...,None,None,"Based on the image provided, there is no visib...","Based on the image provided, there is no visib...","no, not flooded",0.997717,False
4,nexar_9eab3d72765f7764cd4d1f0171cac6ba,Analyze and estimate the deepest floodwater le...,/share/ju/nexar_data/2023/2023-09-29/604222323...,None,None,"Based on the image provided, the floodwater le...","Based on the image provided, the floodwater le...","yes, flooded",0.990876,True

In [4]:
lyu_basic_nli['nli_label'].value_counts()

nli_label
yes, flooded       53525
no, not flooded    39096
Name: count, dtype: int64

In [5]:
# randomly sample 250 rows from each class and write to csv 
lyu_basic_nli_samples = lyu_basic_nli.groupby('nli_label').apply(lambda x: x.sample(250))
lyu_basic_nli_samples.to_csv("/share/pierson/matt/mllmsci/outputs/vqa/bayflood_926k_10pct_lyu_basic_with_nli_samples.csv", index=False)

/tmp/ipykernel_2848249/2619138995.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  lyu_basic_nli_samples = lyu_basic_nli.groupby('nli_label').apply(lambda x: x.sample(250))

In [6]:
# now lyu advanced 
lyu_advanced_nli = pd.read_parquet("/share/pierson/matt/mllmsci/outputs/vqa/bayflood_926k_10pct_lyu_advanced_with_nli_20260120.parquet")

In [7]:
lyu_advanced_nli.head()

,sample_id,prompt,image_path,image_url,image_base64,answer,model_response,nli_label,nli_score,nli_is_flooded
0,nexar_53afeec954a80d924012432cb70c1081,As an expert in assessing floodwater levels fr...,/share/ju/nexar_data/2023/2023-09-29/604222325...,None,None,Based on the provided image and the guidelines...,Based on the provided image and the guidelines...,"yes, flooded",0.995900,True
1,nexar_66384e02c4b2ceda1b331f44ee45e950,As an expert in assessing floodwater levels fr...,/share/ju/nexar_data/2023/2023-09-29/604222325...,None,None,"Given the image provided, it is not possible t...","Given the image provided, it is not possible t...","no, not flooded",0.845852,False
2,nexar_85283d2860cd54b22ccef4a210602830,As an expert in assessing floodwater levels fr...,/share/ju/nexar_data/2023/2023-09-29/604222325...,None,None,Reference Floodwater Level:\n- White car: No v...,Reference Floodwater Level:\n- White car: No v...,"no, not flooded",0.962260,False
3,nexar_4bba636e205d574c150ba661ba3d5e35,As an expert in assessing floodwater levels fr...,/share/ju/nexar_data/2023/2023-09-29/604222325...,None,None,"Given the provided image, it is not possible t...","Given the provided image, it is not possible t...","no, not flooded",0.994305,False
4,nexar_9eab3d72765f7764cd4d1f0171cac6ba,As an expert in assessing floodwater levels fr...,/share/ju/nexar_data/2023/2023-09-29/604222323...,None,None,"Given the provided image, it is not possible t...","Given the provided image, it is not possible t...","no, not flooded",0.945556,False

In [8]:
lyu_advanced_nli['nli_label'].value_counts()

nli_label
no, not flooded    84652
yes, flooded        7969
Name: count, dtype: int64

In [9]:
# randomly sample 250 rows from each class and write to csv 
lyu_advanced_nli_samples = lyu_advanced_nli.groupby('nli_label').apply(lambda x: x.sample(250))
lyu_advanced_nli_samples.to_csv("/share/pierson/matt/mllmsci/outputs/vqa/bayflood_926k_10pct_lyu_advanced_with_nli_samples.csv", index=False)

/tmp/ipykernel_2848249/3395609038.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  lyu_advanced_nli_samples = lyu_advanced_nli.groupby('nli_label').apply(lambda x: x.sample(250))

In [10]:
# now do yang advanced 
yang_advanced_nli = pd.read_parquet("/share/pierson/matt/mllmsci/outputs/vqa/bayflood_926k_10pct_yang_advanced_with_nli.parquet")

In [11]:
yang_advanced_nli['nli_label'].value_counts()

nli_label
no, not flooded    92354
yes, flooded         267
Name: count, dtype: int64

In [12]:
# randomly sample 250 rows from each class and write to csv 
yang_advanced_nli_samples = yang_advanced_nli.groupby('nli_label').apply(lambda x: x.sample(250))
yang_advanced_nli_samples.to_csv("/share/pierson/matt/mllmsci/outputs/vqa/bayflood_926k_10pct_yang_advanced_with_nli_samples.csv", index=False)

/tmp/ipykernel_2848249/3802877598.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  yang_advanced_nli_samples = yang_advanced_nli.groupby('nli_label').apply(lambda x: x.sample(250))

In [13]:
# now, liu floodvision 
liu_floodvision_nli = pd.read_parquet("/share/pierson/matt/mllmsci/outputs/vqa/bayflood_926k_10pct_liu_floodvision_with_nli.parquet")

In [14]:
liu_floodvision_nli['nli_label'].value_counts()

nli_label
yes, passable       68175
uncertain           24043
no, not passable      392
not applicable         11
Name: count, dtype: int64

In [19]:
# randomly sample 250 rows from 'no, not passable' and union of all other classes 
liu_floodvision_not_passable_sample = liu_floodvision_nli[liu_floodvision_nli['nli_label'] == 'no, not passable'].sample(250)
liu_floodvision_other_sample = liu_floodvision_nli[liu_floodvision_nli['nli_label'] != 'no, not passable'].sample(250)
liu_floodvision_samples = pd.concat([liu_floodvision_not_passable_sample, liu_floodvision_other_sample])

liu_floodvision_samples['nli_label'].value_counts()

# now, liu floodvision

nli_label
no, not passable    250
yes, passable       193
uncertain            57
Name: count, dtype: int64

In [20]:
liu_floodvision_samples.to_csv("/share/pierson/matt/mllmsci/outputs/vqa/bayflood_926k_10pct_liu_floodvision_with_nli_samples.csv", index=False)